const { generateId } = require('./helpers');

function generateInsights(merchantId) {
  return [
    {
      insightId: generateId('INS', 1),
      merchantId,
      type: 'recovery_pattern',
      title: 'UPI recovers 2.4x more card failures',
      description: 'When card payments fail due to issuer decline, offering UPI as an alternative recovers 2.4 times more payments compared to retrying the same card.',
      impact: 'High',
      impactAmount: 142000,
      evidence: 'Based on 382 card failures analyzed over the last 30 days.',
      timePeriod: 'Last 30 days',
      sampleSize: 382,
      confidence: 91,
      recommendedAction: 'Set UPI as the default recovery method for card issuer declines.',
      category: 'recovery',
      priority: 95,
      isActionable: true,
    },
    {
      insightId: generateId('INS', 2),
      merchantId,
      type: 'behavioral',
      title: 'Payment failures spike between 8–10 PM',
      description: 'Payment failures between 8 PM and 10 PM have 18% lower recovery rate compared to other hours. This correlates with peak banking system load.',
      impact: 'Medium',
      impactAmount: 31400,
      evidence: 'Analysis of 1,247 payments across different time windows.',
      timePeriod: 'Last 30 days',
      sampleSize: 1247,
      confidence: 84,
      recommendedAction: 'Consider delaying retry attempts for failures during 8-10 PM by 45 minutes for higher success.',
      category: 'timing',
      priority: 72,
      isActionable: true,
    },
    {
      insightId: generateId('INS', 3),
      merchantId,
      type: 'risk_trend',
      title: 'High-value payments (>₹50K) need manual review',
      description: 'Payments above ₹50,000 have a 3.2x higher risk score and require manual review more frequently. Auto-recovery for these transactions has a lower safety rating.',
      impact: 'High',
      impactAmount: 85000,
      evidence: 'Based on 67 high-value transactions in the last 30 days.',
      timePeriod: 'Last 30 days',
      sampleSize: 67,
      confidence: 88,
      recommendedAction: 'Set manual review threshold at ₹50,000 for autopilot.',
      category: 'risk',
      priority: 88,
      isActionable: true,
    },
    {
      insightId: generateId('INS', 4),
      merchantId,
      type: 'revenue_opportunity',
      title: '₹31,400/month additional recovery possible',
      description: 'By optimizing retry timing for network timeout failures, an additional ₹31,400 per month in revenue could potentially be recovered.',
      impact: 'Medium',
      impactAmount: 31400,
      evidence: 'Modelled from 156 network timeout failures and their recovery patterns.',
      timePeriod: 'Last 30 days',
      sampleSize: 156,
      confidence: 76,
      recommendedAction: 'Enable delayed retry (45 seconds) for network timeout failures.',
      category: 'revenue',
      priority: 80,
      isActionable: true,
    },
    {
      insightId: generateId('INS', 5),
      merchantId,
      type: 'settlement_pattern',
      title: 'Settlement variance averaging ₹320/day',
      description: 'Small settlement adjustments are occurring on approximately 15% of settled payments. While individually minor, they aggregate to an average daily variance of ₹320.',
      impact: 'Low',
      impactAmount: 9600,
      evidence: 'Analysis of 200 settlements over the last 30 days.',
      timePeriod: 'Last 30 days',
      sampleSize: 200,
      confidence: 82,
      recommendedAction: 'Review fee structure with Razorpay for potential optimization.',
      category: 'settlement',
      priority: 55,
      isActionable: true,
    },
    {
      insightId: generateId('INS', 6),
      merchantId,
      type: 'recovery_pattern',
      title: 'Payment links recover abandoned checkouts 63% of the time',
      description: 'For abandoned checkout scenarios with high customer intent, sending a payment link within 15 minutes recovers 63% of transactions.',
      impact: 'High',
      impactAmount: 96000,
      evidence: 'Based on 178 abandoned checkout recoveries.',
      timePeriod: 'Last 30 days',
      sampleSize: 178,
      confidence: 87,
      recommendedAction: 'Enable automatic payment link for abandoned checkouts with intent > 70%.',
      category: 'recovery',
      priority: 85,
      isActionable: true,
    },
  ];
}

function generatePlaybook(merchantId) {
  return [
    {
      playbookId: generateId('PB', 1),
      merchantId,
      scenario: 'Card payment fails due to issuer decline',
      scenarioType: 'card_failure',
      recommendedAction: 'offer_upi',
      successRate: 76,
      sampleSize: 382,
      confidence: 91,
      averageRecoveryAmount: 4200,
      lastUpdated: new Date(Date.now() - 14 * 86400000),
    },
    {
      playbookId: generateId('PB', 2),
      merchantId,
      scenario: 'UPI payment times out',
      scenarioType: 'upi_timeout',
      recommendedAction: 'retry_same_method',
      successRate: 68,
      sampleSize: 245,
      confidence: 87,
      averageRecoveryAmount: 2800,
      lastUpdated: new Date(Date.now() - 7 * 86400000),
    },
    {
      playbookId: generateId('PB', 3),
      merchantId,
      scenario: 'High-value payment (>₹50,000)',
      scenarioType: 'high_value',
      recommendedAction: 'manual_review',
      successRate: 91,
      sampleSize: 67,
      confidence: 84,
      averageRecoveryAmount: 62000,
      lastUpdated: new Date(Date.now() - 3 * 86400000),
    },
    {
      playbookId: generateId('PB', 4),
      merchantId,
      scenario: 'Customer abandons checkout',
      scenarioType: 'abandoned_checkout',
      recommendedAction: 'send_payment_link',
      successRate: 63,
      sampleSize: 178,
      confidence: 87,
      averageRecoveryAmount: 3100,
      lastUpdated: new Date(Date.now() - 5 * 86400000),
    },
    {
      playbookId: generateId('PB', 5),
      merchantId,
      scenario: 'Repeated payment failures from same customer',
      scenarioType: 'repeat_failure',
      recommendedAction: 'send_payment_link',
      successRate: 52,
      sampleSize: 94,
      confidence: 73,
      averageRecoveryAmount: 1800,
      lastUpdated: new Date(Date.now() - 10 * 86400000),
    },
    {
      playbookId: generateId('PB', 6),
      merchantId,
      scenario: 'New customer first payment fails',
      scenarioType: 'new_customer',
      recommendedAction: 'offer_upi',
      successRate: 58,
      sampleSize: 156,
      confidence: 79,
      averageRecoveryAmount: 2200,
      lastUpdated: new Date(Date.now() - 8 * 86400000),
    },
    {
      playbookId: generateId('PB', 7),
      merchantId,
      scenario: 'Bank decline during business hours',
      scenarioType: 'bank_decline',
      recommendedAction: 'retry_later',
      successRate: 71,
      sampleSize: 203,
      confidence: 85,
      averageRecoveryAmount: 3400,
      lastUpdated: new Date(Date.now() - 6 * 86400000),
    },
  ];
}

module.exports = { generateInsights, generatePlaybook };
