const { generateId } = require('./helpers');

function generateInsights(merchantId) {
  return [
    {
      insightId: generateId('INS', 1),
      merchantId,
      type: 'recovery_pattern',
      title: 'UPI recovers 2.4x more card failures',
      description: 'When card payments fail due to issuer decline, offering UPI as an alternative recovers 2.4 times more payments compared to retrying the same card.',
      impact: 'High',
      impactAmount: 142000,
      evidence: 'Based on 382 card failures analyzed over the last 30 days.',
      timePeriod: 'Last 30 days',
      sampleSize: 382,
      confidence: 91,
      recommendedAction: 'Maintain UPI as primary automated recovery strategy for card issuer declines.',
      category: 'recovery',
      priority: 95,
      isActionable: true,
    },
    {
      insightId: generateId('INS', 2),
      merchantId,
      type: 'behavioral',
      title: 'Payment failures spike between 8–10 PM',
      description: 'Payment failures between 8 PM and 10 PM have 18% lower recovery rate compared to other hours due to peak banking gateway traffic and load clearance.',
      impact: 'Medium',
      impactAmount: 31400,
      evidence: 'Analysis of 1,247 payments across different time windows.',
      timePeriod: 'Last 30 days',
      sampleSize: 1247,
      confidence: 84,
      recommendedAction: 'Delay retry triggers by approximately 45 seconds during peak hours.',
      category: 'timing',
      priority: 72,
      isActionable: true,
    },
    {
      insightId: generateId('INS', 3),
      merchantId,
      type: 'risk_trend',
      title: 'High-value payments above ₹50,000 have elevated fraud probability',
      description: 'Transactions above ₹50,000 exhibit a 3.2x higher incidence of synthetic risk markers and velocity anomalies.',
      impact: 'High',
      impactAmount: 85000,
      evidence: 'Based on 67 high-value transactions in the last 30 days.',
      timePeriod: 'Last 30 days',
      sampleSize: 67,
      confidence: 88,
      recommendedAction: 'Require verification before recovery.',
      category: 'risk',
      priority: 88,
      isActionable: true,
    },
    {
      insightId: generateId('INS', 4),
      merchantId,
      type: 'revenue_opportunity',
      title: 'Smart Retry Timing can generate approximately ₹31,400/month additional modeled recovery',
      description: 'By dynamically spacing retry triggers based on banking gateway responsiveness rather than immediate retry, approximately ₹31,400 per month can be recovered (Modeled / simulated).',
      impact: 'Medium',
      impactAmount: 31400,
      evidence: 'Derived from 156 network timeout and bank gateway latency patterns.',
      timePeriod: 'Last 30 days',
      sampleSize: 156,
      confidence: 76,
      recommendedAction: 'Enable Smart Delay Retry for bank network latency spikes.',
      category: 'revenue',
      priority: 80,
      isActionable: true,
    },
    {
      insightId: generateId('INS', 5),
      merchantId,
      type: 'recovery_pattern',
      title: 'High-intent cart abandonment recovers 63% via payment links',
      description: 'Customers with high intent (intent score > 70%) who abandon checkout recover at 63% when sent a direct payment link within 15 minutes.',
      impact: 'High',
      impactAmount: 96000,
      evidence: 'Based on 178 abandoned checkout events analyzed.',
      timePeriod: 'Last 30 days',
      sampleSize: 178,
      confidence: 82,
      recommendedAction: 'Send automated payment link for abandoned checkouts with high intent.',
      category: 'recovery',
      priority: 85,
      isActionable: true,
    },
  ];
}

function generatePlaybook(merchantId) {
  return [
    {
      playbookId: generateId('PB', 1),
      merchantId,
      scenario: 'Card issuer decline → Offer UPI',
      scenarioType: 'card_failure',
      recommendedAction: 'offer_upi',
      successRate: 76,
      sampleSize: 382,
      confidence: 91,
      averageRecoveryAmount: 4200,
      lastUpdated: new Date(Date.now() - 14 * 86400000),
    },
    {
      playbookId: generateId('PB', 2),
      merchantId,
      scenario: 'UPI timeout → Retry after 45 seconds',
      scenarioType: 'upi_timeout',
      recommendedAction: 'retry_same_method',
      successRate: 68,
      sampleSize: 245,
      confidence: 87,
      averageRecoveryAmount: 2800,
      lastUpdated: new Date(Date.now() - 7 * 86400000),
    },
    {
      playbookId: generateId('PB', 3),
      merchantId,
      scenario: 'High-value payment > ₹50,000 with anomaly signals → Manual review',
      scenarioType: 'high_value',
      recommendedAction: 'manual_review',
      successRate: 91,
      sampleSize: 67,
      confidence: 84,
      averageRecoveryAmount: 62000,
      lastUpdated: new Date(Date.now() - 3 * 86400000),
    },
    {
      playbookId: generateId('PB', 4),
      merchantId,
      scenario: 'High-intent abandoned checkout → Send payment link',
      scenarioType: 'abandoned_checkout',
      recommendedAction: 'send_payment_link',
      successRate: 63,
      sampleSize: 178,
      confidence: 82,
      averageRecoveryAmount: 3100,
      lastUpdated: new Date(Date.now() - 5 * 86400000),
    },
    {
      playbookId: generateId('PB', 5),
      merchantId,
      scenario: 'Network timeout during peak hours → Smart retry later',
      scenarioType: 'bank_decline',
      recommendedAction: 'retry_later',
      successRate: 68,
      sampleSize: 312,
      confidence: 84,
      averageRecoveryAmount: 3400,
      lastUpdated: new Date(Date.now() - 6 * 86400000),
    },
  ];
}

module.exports = { generateInsights, generatePlaybook };
